### ISSUE TITLE
缺少c5_pug

### ISSUE THREAD

**Issue by If1337** [Cola-Ace/VIP-plugin#4]
[SM] Unable to load plugin "vip_extrusion.smx": Could not find required plugin "c5_pug"
c5_pug在哪下呀，找不到

**Comment by Cola-Ace** [comment]
> [SM] Unable to load plugin "vip_extrusion.smx": Could not find required plugin "c5_pug"
> c5_pug在哪下呀，找不到

下个版本修复

**Comment by If1337** [comment]
> > [SM] Unable to load plugin "vip_extrusion.smx": Could not find required plugin "c5_pug"
> > c5_pug在哪下呀，找不到
> 
> 下个版本修复

好的

**Comment by If1337** [comment]
可是能不能发我一份，我还有其他插件需要这个，谢谢啦

**Comment by Cola-Ace** [comment]
> 可是能不能发我一份，我还有其他插件需要这个，谢谢啦

加我q 2591668626

**Comment by Cola-Ace** [comment]
问题已修复，现在不需要装c5_pug也能正常使用插件了

**Comment by If1337** [comment]
感谢
